### ISSUE TITLE
Permissions issue

### ISSUE THREAD

**Issue by spankurmonkey** [EricZimmerman/VoronTools#1]
Eric - your steps for canbus setup was shared with me on FB group.   I followed all of the steps outlined up to the point where it came to test by making the test fan changes.

I couldn't see any of my cfg files and the ebb board file was read only.

I found my cfg files and moved them to printer data but again they were all read only.

Before this process I didn;t have any permissions issues.

**Comment by EricZimmerman** [comment]
Well my directions wouldn't cause that issue. 

With that said I have no idea what your printer is, what commands you ran, what the state was before, if you updated moonraker or other printer software, etc. 

Not sure what you are looking for here.
