### ISSUE TITLE
Backing Up Printer Configuration Files to GitHub

### ISSUE THREAD

**Issue by dburke555** [EricZimmerman/VoronTools#2]
Hello!  I Recently followed, what I believe were your instructions, on the vorondesign.com site, for setting up printer configuration file backups on GitHub.  I got all the way through the procedure, but when I ran the Macro via Fluid, I get an error message saying "access to .get folders is forbidden".  Any idea how to resolve this?

**Comment by EricZimmerman** [comment]
Hard to say. Does it work when run from the pi? The sh file I mean.

**Comment by dburke555** [comment]
Thank you for responding!  After having powered down the printer last night and then firing it back up this morning.  I tried executing the script from the terminal window via SSH, and it worked.  I then tried it again from the Fluid UI, via the macro and it now works!  I guess a reboot resolved the issue.

**Comment by EricZimmerman** [comment]
excellent!
