### ISSUE TITLE
Prusa error

### ISSUE THREAD

**Issue by rhawley88** [EricZimmerman/VoronTools#4]
M104 S0 ; Stops PS/SS from sending temp waits separately
M140 S0
PRINT_START BED_TEMP=[first_layer_bed_temperature] EXTRUDER_TEMP={first_layer_temperature[initial_extruder]+extruder_temperature_offset[initial_extruder]} CHAMBER_TEMP=[chamber_temperature] SIZE={first_layer_print_min[0]}_{first_layer_print_min[1]}_{first_layer_print_max[0]}_{first_layer_print_max[1]} MATERIAL={filament_type} 

gives an error in prusa

start_gcode
Parsing error at line 6: Not a variable name
EXTRUDER_TEMP={first_layer_temperature[initial_extruder]+extruder_temperature_offset[initial_extruder]} 
                                                         ^

**Comment by EricZimmerman** [comment]
I don't use Prusa slicer

No idea
