### ISSUE TITLE
Canboot Changed to Katapult

### ISSUE THREAD

**Issue by Malygros** [EricZimmerman/VoronTools#6]
When you make the .bin file it says no more "canboot.bin" Canboot changed to Katapult. 

You must change some parts. The important one is this here:

sudo dfu-util -a 0 -D ~/CanBoot/out/canboot.bin --dfuse-address 0x08000000:force:mass-erase:leave -d 0483:df11

to

sudo dfu-util -a 0 -D ~/CanBoot/out/katapult.bin --dfuse-address 0x08000000:force:mass-erase:leave -d 0483:df11

**Comment by EricZimmerman** [comment]
Got a reference to this change?

**Comment by Malygros** [comment]
> Got a reference to this change?

https://github.com/Arksine/katapult

**Comment by EricZimmerman** [comment]
this is gonna be a bit off for new installs, since it would be ~/katapult/ directory. ill make notes as needed.

this is now done
