### ISSUE TITLE
autocommit.sh and corrupt git files

### ISSUE THREAD

**Issue by noobydp** [EricZimmerman/VoronTools#8]
Hey!
I've been using the autocommit.sh script on 4 of my machines and they seem to regularly throw git errors.
I'm running automatically via crontab.

The output from the command is below. I wasn't sure what else would be helpful or where to start debugging.

Any ideas on how I can stop this happening?

> ./autocommit.sh 
> error: object file .git/objects/63/471ead2b4cc22590a30e98d7de500d2961ffc3 is empty
> fatal: loose object 63471ead2b4cc22590a30e98d7de500d2961ffc3 (stored in .git/objects/63/471ead2b4cc22590a30e98d7de500d2961ffc3) is corrupt
> error: object file .git/objects/63/471ead2b4cc22590a30e98d7de500d2961ffc3 is empty
> error: object file .git/objects/63/471ead2b4cc22590a30e98d7de500d2961ffc3 is empty
> fatal: loose object 63471ead2b4cc22590a30e98d7de500d2961ffc3 (stored in .git/objects/63/471ead2b4cc22590a30e98d7de500d2961ffc3) is corrupt
> Everything up-to-date

**Comment by EricZimmerman** [comment]
How are you shutting your printer off at the end of the day?

**Comment by noobydp** [comment]
I.... flip the wall power switch 🙃

**Comment by EricZimmerman** [comment]
There's your problem. Never ever ever ever do that

You are introducing corruption into the file system when you do that which is leading to the thing that you're seeing here

Always shut things down via the option in mainsail or equivalent

You can certainly delete those zero byte files in an attempt to clean it up but the issue should go away once you get things committed and stop doing hard shutdowns like that

The script itself would have no way of introducing zero byte files or anything else like that as it's simply just backing up things in your printer config directories some of which may now be corrupted

**Comment by noobydp** [comment]
cool I'll give that a go, thanks for replying so fast.
